version: '3'
services:
  back:
    image: back
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
  
  front:
    image: front
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - back