version: '3'
services:
  back:
    image: syd-back:0.1
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
  
  front:
    image: syd-front:0.1
    build:
      context: ./front
      dockerfile: Dockerfile.local
    ports:
      - 8080:80
    networks:
      - my_network
    
  api:
    image: back
    container_name: syd-back
    build:
      context: ./back
      dockerfile: Dockerfile.local
    ports:
      - 8000:8000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge