# Generated by Django 5.0.6 on 2024-08-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSVFile',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='csv',
            new_name='file',
        ),
    ]
