FROM python:3.12-slim

WORKDIR /back

COPY . ./

RUN pip install --no-cache-dir -r /back/requirements.txt && \
    export SECRET_KEY=temp_key_for_build && \
    python3 manage.py makemigrations && \
    python3 manage.py migrate

EXPOSE 8000

CMD ["gunicorn", "config.wsgi", "--bind", "0.0.0.0:8000"]