FROM python:3.12-slim

WORKDIR /back

COPY . ./

RUN pip install --no-cache-dir -r /back/requirements.txt
RUN python3 manage.py makemigrations
RUN python3 manage.py migrate

EXPOSE 8000

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000", "--settings=config.django.local"]